using System;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity;
using RAGKnowledgeBase.Core.Application.Auth.DTOs;
using RAGKnowledgeBase.Core.Application.Auth.Interfaces;
using RAGKnowledgeBase.Core.Application.Exceptions;
using RAGKnowledgeBase.Infrastructure.Identity;
using RAGKnowledgeBase.Infrastructure.Identity.Services;

namespace RAGKnowledgeBase.Infrastructure.Identity.Services;

public class AuthService : IAuthService
{
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly IJwtTokenGenerator _jwtGenerator;

    public AuthService(UserManager<ApplicationUser> userManager, IJwtTokenGenerator jwtGenerator)
    {
        _userManager = userManager ?? throw new ArgumentNullException(nameof(userManager));
        _jwtGenerator = jwtGenerator ?? throw new ArgumentNullException(nameof(jwtGenerator));
    }

    public async Task<AuthResponse> LoginAsync(LoginRequest request)
    {
        if (request is null) throw new BadRequestException("Request is null");
        if (string.IsNullOrWhiteSpace(request.Email) || string.IsNullOrWhiteSpace(request.Password))
            throw new BadRequestException("Email and password are required.");

        var user = await _userManager.FindByEmailAsync(request.Email);
        if (user == null || !await _userManager.CheckPasswordAsync(user, request.Password))
            throw new UnauthorizedException("Invalid credentials.");

        var roles = (await _userManager.GetRolesAsync(user))?.ToList() ?? new List<string>();
        var token = _jwtGenerator.GenerateToken(user.Id, user.Email ?? string.Empty, roles);
        var refreshToken = GenerateRefreshToken(user.Id);

        return new AuthResponse(token, refreshToken, user.Id, user.Email ?? string.Empty, user.FullName);
    }

    public async Task<AuthResponse> RegisterAsync(RegisterRequest request)
    {
        if (request is null) throw new BadRequestException("Request is null");
        if (string.IsNullOrWhiteSpace(request.Email) || string.IsNullOrWhiteSpace(request.Password) || string.IsNullOrWhiteSpace(request.FullName))
            throw new BadRequestException("Email, password and full name are required.");

        var existing = await _userManager.FindByEmailAsync(request.Email);
        if (existing != null) throw new BadRequestException("A user with this email already exists.");

        var user = new ApplicationUser
        {
            UserName = request.Email,
            Email = request.Email,
            FullName = request.FullName,
            IsActive = true,
        };

        var result = await _userManager.CreateAsync(user, request.Password);
        if (!result.Succeeded)
        {
            var errors = string.Join("; ", result.Errors.Select(e => e.Description));
            throw new BadRequestException($"User creation failed: {errors}");
        }

        var roles = new List<string>();
        var token = _jwtGenerator.GenerateToken(user.Id, user.Email ?? string.Empty, roles);
        var refreshToken = GenerateRefreshToken(user.Id);

        return new AuthResponse(token, refreshToken, user.Id, user.Email ?? string.Empty, user.FullName);
    }

    public async Task<AuthResponse> RefreshTokenAsync(string refreshToken)
    {
        if (string.IsNullOrWhiteSpace(refreshToken)) throw new BadRequestException("Refresh token is required.");

        // Expected format: "{userId}:{nonce}" as generated by this service
        var parts = refreshToken.Split(':', 2);
        if (parts.Length != 2 || !Guid.TryParse(parts[0], out var userId))
            throw new BadRequestException("Invalid refresh token format.");

        var user = await _userManager.FindByIdAsync(userId.ToString());
        if (user == null) throw new UnauthorizedException("User not found for refresh token.");

        var roles = (await _userManager.GetRolesAsync(user))?.ToList() ?? new List<string>();
        var token = _jwtGenerator.GenerateToken(user.Id, user.Email ?? string.Empty, roles);
        var newRefreshToken = GenerateRefreshToken(user.Id);

        return new AuthResponse(token, newRefreshToken, user.Id, user.Email ?? string.Empty, user.FullName);
    }

    private static string GenerateRefreshToken(Guid userId)
    {
        return $"{userId}:{Guid.NewGuid()}";
    }
}
